### ISSUE TITLE
Index out of range while connecting to Mupen64

### ISSUE THREAD

**Issue by xcrafter40** [SM64-TAS-ABC/STROOP#31]
I tried to connect to mupen64 using the latest version, and got this error:
************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at SM64_Diagnostic.StroopMainForm.AttachToProcess(Process process)
   at SM64_Diagnostic.StroopMainForm.buttonConnect_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by onlymx13** [comment]
I get the same issue with Project64 but not Mupen64-RR.

**Comment by danebou** [comment]
This was fixed a while ago. Let me know if this happens on the latest version. Thanks guys!
